namespace Iteration.Orchestrator.Application.Abstractions;

public sealed record SolutionAnalysisRequest(
    Guid WorkflowRunId,
    Guid TargetSolutionId,
    string WorkflowCode,
    string WorkflowName,
    string WorkflowPurpose,
    string RequirementTitle,
    string RequirementDescription,
    string ProfileSummary,
    IReadOnlyList<TextDocumentInput> ProfileRules,
    IReadOnlyList<TextDocumentInput> SolutionKnowledgeDocuments,
    IReadOnlyList<WorkflowArtifactDefinition> ProducedArtifacts,
    IReadOnlyList<string> KnowledgeUpdates,
    IReadOnlyList<string> ExecutionRules,
    IReadOnlyList<string> NextWorkflowCodes,
    IReadOnlyList<string> RepositoryFiles,
    IReadOnlyList<string> RepositoryDocumentationFiles,
    string RepositoryPath,
    IReadOnlyDictionary<string, string> SampleFiles);

public sealed record SolutionAnalysisResult(
    string Summary,
    string Status,
    string ArtifactsJson,
    string GeneratedRequirementsJson,
    string GeneratedOpenQuestionsJson,
    string GeneratedDecisionsJson,
    string DocumentationUpdatesJson,
    string KnowledgeUpdatesJson,
    string RecommendedNextWorkflowCodesJson,
    string RawJson);

public sealed record SolutionDesignRequest(
    Guid WorkflowRunId,
    Guid TargetSolutionId,
    Guid RequirementId,
    Guid AnalysisWorkflowRunId,
    string WorkflowCode,
    string WorkflowName,
    string WorkflowPurpose,
    string RequirementTitle,
    string RequirementDescription,
    string AnalysisSummary,
    string AnalysisStatus,
    string AnalysisArtifactsJson,
    string AnalysisOpenQuestionsJson,
    string AnalysisDecisionsJson,
    string ProfileSummary,
    IReadOnlyList<TextDocumentInput> ProfileRules,
    IReadOnlyList<TextDocumentInput> SolutionKnowledgeDocuments,
    IReadOnlyList<WorkflowArtifactDefinition> ProducedArtifacts,
    IReadOnlyList<string> KnowledgeUpdates,
    IReadOnlyList<string> ExecutionRules,
    IReadOnlyList<string> NextWorkflowCodes,
    IReadOnlyList<string> RepositoryFiles,
    IReadOnlyList<string> RepositoryDocumentationFiles,
    string RepositoryPath,
    IReadOnlyDictionary<string, string> SampleFiles);

public sealed record SolutionDesignResult(
    string Summary,
    string Status,
    string ArtifactsJson,
    string GeneratedOpenQuestionsJson,
    string GeneratedDecisionsJson,
    string DocumentationUpdatesJson,
    string KnowledgeUpdatesJson,
    string RecommendedNextWorkflowCodesJson,
    string RawJson);


public sealed record SolutionPlanRequest(
    Guid WorkflowRunId,
    Guid TargetSolutionId,
    Guid RequirementId,
    Guid DesignWorkflowRunId,
    string WorkflowCode,
    string WorkflowName,
    string WorkflowPurpose,
    string RequirementTitle,
    string RequirementDescription,
    string DesignSummary,
    string DesignStatus,
    string DesignArtifactsJson,
    string DesignOpenQuestionsJson,
    string DesignDecisionsJson,
    string ProfileSummary,
    IReadOnlyList<TextDocumentInput> ProfileRules,
    IReadOnlyList<TextDocumentInput> SolutionKnowledgeDocuments,
    IReadOnlyList<WorkflowArtifactDefinition> ProducedArtifacts,
    IReadOnlyList<string> KnowledgeUpdates,
    IReadOnlyList<string> ExecutionRules,
    IReadOnlyList<string> NextWorkflowCodes,
    IReadOnlyList<string> RepositoryFiles,
    IReadOnlyList<string> RepositoryDocumentationFiles,
    string RepositoryPath,
    IReadOnlyDictionary<string, string> SampleFiles);

public sealed record SolutionPlanResult(
    string Summary,
    string Status,
    string ArtifactsJson,
    string GeneratedBacklogItemsJson,
    string GeneratedOpenQuestionsJson,
    string GeneratedDecisionsJson,
    string DocumentationUpdatesJson,
    string KnowledgeUpdatesJson,
    string RecommendedNextWorkflowCodesJson,
    string RawJson);


public sealed record SolutionImplementationRequest(
    Guid WorkflowRunId,
    Guid TargetSolutionId,
    Guid RequirementId,
    Guid BacklogItemId,
    Guid PlanWorkflowRunId,
    string WorkflowCode,
    string WorkflowName,
    string WorkflowPurpose,
    string RequirementTitle,
    string RequirementDescription,
    string BacklogTitle,
    string BacklogDescription,
    int PlanningOrder,
    string PlanSummary,
    string PlanStatus,
    string GeneratedBacklogItemsJson,
    string PlanOpenQuestionsJson,
    string PlanDecisionsJson,
    string ProfileSummary,
    IReadOnlyList<TextDocumentInput> ProfileRules,
    IReadOnlyList<TextDocumentInput> SolutionKnowledgeDocuments,
    IReadOnlyList<WorkflowArtifactDefinition> ProducedArtifacts,
    IReadOnlyList<string> KnowledgeUpdates,
    IReadOnlyList<string> ExecutionRules,
    IReadOnlyList<string> NextWorkflowCodes,
    IReadOnlyList<string> RepositoryFiles,
    IReadOnlyList<string> RepositoryDocumentationFiles,
    string RepositoryPath,
    IReadOnlyDictionary<string, string> SampleFiles);

public sealed record SolutionImplementationResult(
    string Summary,
    string Status,
    string ImplementedChangesJson,
    string FilesTouchedJson,
    string TestsExecutedJson,
    string GeneratedRequirementsJson,
    string GeneratedOpenQuestionsJson,
    string GeneratedDecisionsJson,
    string DocumentationUpdatesJson,
    string KnowledgeUpdatesJson,
    string RecommendedNextWorkflowCodesJson,
    string RawJson);
