// <auto-generated />
using System;
using Iteration.Orchestrator.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Iteration.Orchestrator.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416101135_InitialOrchestratorModel")]
    partial class InitialOrchestratorModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Iteration.Orchestrator.Domain.Backlog.BacklogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetSolutionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BacklogItems");
                });

            modelBuilder.Entity("Iteration.Orchestrator.Domain.Reports.AnalysisReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentationUpdatesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedDecisionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedOpenQuestionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedRequirementsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KnowledgeUpdatesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawOutputJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendedNextWorkflowCodesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AnalysisReports");
                });

            modelBuilder.Entity("Iteration.Orchestrator.Domain.Solutions.SolutionTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MainSolutionFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SolutionOverlayCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SolutionTargets");
                });

            modelBuilder.Entity("Iteration.Orchestrator.Domain.Workflows.AgentTaskRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputPayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AgentTaskRuns");
                });

            modelBuilder.Entity("Iteration.Orchestrator.Domain.Workflows.WorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BacklogItemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetSolutionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkflowRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
