// <auto-generated />
using System;
using Iteration.Orchestrator.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Iteration.Orchestrator.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416102926_AddRequirements")]
    partial class AddRequirements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Iteration.Orchestrator.Domain.Backlog.BacklogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetSolutionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BacklogItems");
                });

            modelBuilder.Entity("Iteration.Orchestrator.Domain.Decisions.Decision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlternativesConsideredJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BacklogItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsequencesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rationale")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RequirementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetSolutionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkflowRunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BacklogItemId");

                    b.HasIndex("RequirementId");

                    b.HasIndex("TargetSolutionId");

                    b.HasIndex("WorkflowRunId");

                    b.ToTable("Decisions");
                });

            modelBuilder.Entity("Iteration.Orchestrator.Domain.Questions.OpenQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BacklogItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RequirementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetSolutionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkflowRunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BacklogItemId");

                    b.HasIndex("RequirementId");

                    b.HasIndex("TargetSolutionId");

                    b.HasIndex("WorkflowRunId");

                    b.ToTable("OpenQuestions");
                });

            modelBuilder.Entity("Iteration.Orchestrator.Domain.Reports.AnalysisReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentationUpdatesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedDecisionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedOpenQuestionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedRequirementsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KnowledgeUpdatesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawOutputJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendedNextWorkflowCodesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AnalysisReports");
                });

            modelBuilder.Entity("Iteration.Orchestrator.Domain.Requirements.Requirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AcceptanceCriteriaJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConstraintsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OriginatingBacklogItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentRequirementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequirementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetSolutionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkflowRunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OriginatingBacklogItemId");

                    b.HasIndex("ParentRequirementId");

                    b.HasIndex("TargetSolutionId");

                    b.HasIndex("WorkflowRunId");

                    b.ToTable("Requirements");
                });

            modelBuilder.Entity("Iteration.Orchestrator.Domain.Solutions.SolutionTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MainSolutionFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SolutionOverlayCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SolutionTargets");
                });

            modelBuilder.Entity("Iteration.Orchestrator.Domain.Workflows.AgentTaskRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputPayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AgentTaskRuns");
                });

            modelBuilder.Entity("Iteration.Orchestrator.Domain.Workflows.WorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BacklogItemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetSolutionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkflowRuns");
                });

            modelBuilder.Entity("Iteration.Orchestrator.Domain.Decisions.Decision", b =>
                {
                    b.HasOne("Iteration.Orchestrator.Domain.Backlog.BacklogItem", null)
                        .WithMany()
                        .HasForeignKey("BacklogItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Iteration.Orchestrator.Domain.Requirements.Requirement", null)
                        .WithMany()
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Iteration.Orchestrator.Domain.Solutions.SolutionTarget", null)
                        .WithMany()
                        .HasForeignKey("TargetSolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Iteration.Orchestrator.Domain.Workflows.WorkflowRun", null)
                        .WithMany()
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Iteration.Orchestrator.Domain.Questions.OpenQuestion", b =>
                {
                    b.HasOne("Iteration.Orchestrator.Domain.Backlog.BacklogItem", null)
                        .WithMany()
                        .HasForeignKey("BacklogItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Iteration.Orchestrator.Domain.Requirements.Requirement", null)
                        .WithMany()
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Iteration.Orchestrator.Domain.Solutions.SolutionTarget", null)
                        .WithMany()
                        .HasForeignKey("TargetSolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Iteration.Orchestrator.Domain.Workflows.WorkflowRun", null)
                        .WithMany()
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Iteration.Orchestrator.Domain.Requirements.Requirement", b =>
                {
                    b.HasOne("Iteration.Orchestrator.Domain.Backlog.BacklogItem", null)
                        .WithMany()
                        .HasForeignKey("OriginatingBacklogItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Iteration.Orchestrator.Domain.Requirements.Requirement", null)
                        .WithMany()
                        .HasForeignKey("ParentRequirementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Iteration.Orchestrator.Domain.Solutions.SolutionTarget", null)
                        .WithMany()
                        .HasForeignKey("TargetSolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Iteration.Orchestrator.Domain.Workflows.WorkflowRun", null)
                        .WithMany()
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
